---
title: "HW4-AR Peters - Syntax and Output"
output: html_document
---

PSY 5013

Dr. Song

```{r, echo=FALSE}
library(foreign)
library(knitr)
```

```{r, echo=FALSE}
ds<-read.table("Student_Survey_Data.dat")
colnames(ds)<-c("ID", "Gender", "Age", "Party", "Marijuana")
```

Question 1:

```{r}
ds$Female<-ifelse(ds$Gender==1, 0, 1)
MarijuanaByGender<-lm(Marijuana~Female, data=ds)
summary(MarijuanaByGender)
```

Question 2:
```{r}
ds$DEM<-ifelse(ds$Party==2, 1, 0)
ds$IND<-ifelse(ds$Party==3, 1, 0)
MarijuanaByParty<-(lm(Marijuana~DEM+IND, data=ds))
summary(MarijuanaByParty)
```

Question 3:
```{r}
ds$DEMUE<-ifelse(ds$Party==2, 1, ifelse(ds$Party==1, 0, -1))
ds$REPUE<-ifelse(ds$Party==1, 1, ifelse(ds$Party==2, 0, -1))
MarijuanaByParty<-(lm(Marijuana~DEMUE+REPUE, data=ds))
summary(MarijuanaByParty)
```

Question 4:
```{r}
ds$DIvsR<-ifelse(ds$Party==1, -2/3, 1/3)
ds$DvsI<-ifelse(ds$Party==1, 0, ifelse(ds$Party==2, 1/2, -1/2))
MarijuanaByParty<-lm(Marijuana~DIvsR+DvsI, data=ds)
summary(MarijuanaByParty)
```

Question 5:

```{r}
MarijuanaByParty<-(lm(Marijuana~DEM+IND+Age, data=ds))
summary(MarijuanaByParty)
```